### ISSUE TITLE
nasm-mode prevents completion-at-point in sh-mode

### ISSUE THREAD

**Issue by tuhdo** [skeeto/nasm-mode#5]
After installing `nasm-mode` and load it, `completion-at-point` in sh-mode no longer give code completion, but giving this error instead:

```
user-error: No items suitable for an index found in this buffer
```

**Comment by skeeto** [comment]
I'm not able to reproduce this. What version of Emacs are you using?

**Comment by tuhdo** [comment]
I'm using Emacs 24.5.1. I can reproduce it from stock Emacs, load MELPA, install the package then load it.

**Comment by skeeto** [comment]
Ok, I think I understand your problem now, and I can reproduce it on
24.4 as well. Looks to me like this is a bug in sh-mode. The problem
occurs just by loading imenu, which is required by nasm-mode. Here's how
you can reproduce without involving nasm-mode:

   emacs -Q --eval "(require 'imenu)"

Loading imenu breaks completion sh-mode.

**Comment by tuhdo** [comment]
I see. Thanks  for finding out the cause.

**Comment by jgarvin** [comment]
@tuhdo did you ever find a fix or workaround for this? the only mentions I can find are your bugs
